### PR TITLE
add SGC-PN model

### PR DESCRIPTION
**Pull request by feng-y16**
Based on *PairNorm: Tackling Oversmoothing in GNNs* (link: https://arxiv.org/abs/1909.12223, source code: https://github.com/LingxiaoShawn/PairNorm)
Contributor: Yao Feng

### CODE REVIEW

**Comment by cenyk1230** [comment]
Hi @feng-y16,

Thank you for contributing to the CogDL. The model should be also tested. You can add one test in `tests/tasks/node_classification.py` to ensure the model is covered in the testing. In the meanwhile, you should add the results of the new model to our leaderboard in the README (https://github.com/THUDM/cogdl#semi-supervised-node-classification-with-attributes).

**Comment by cenyk1230** [comment]
Are there any ways to add only three datasets (cora-missing, citeseer-missing, and pubmed-missing) and pass the missing rate (0/20/40/60/80/100) as input arguments?

**Comment by feng-y16** [comment]
I see. It seems that the dataset classes cannot add arguments to the parser, so I am not sure.

**Comment by cenyk1230** [comment]
Sorry, I will try to implement the feature to support dataset arguments.

**Comment by cenyk1230** [comment]
Maybe we can add the missing rate argument in the `node_classification` task and process the data in the `__init__` function of `node_classification` task.

**Comment by feng-y16** [comment]
I fixed the issues.

**Comment by cenyk1230** [comment]
From the build, it seems you should set `missing_rate=-1` in the `get_default_args` in the `test_node_classification.py`.

**Pull request merged**
