### PR TITLE
[Quality] tests for AttributedGraphClustering

### PR DESCRIPTION
**Pull request by MaLiN2223**
Adding simple tests for AttributedGraphClustering. 
If the form is good, I can introduce more. 
The overall idea is to make tests to actually test what the classes are doing, currently it seems that tests are checking 'if the model finishes'. 

Also, a question to the reviewer - is there any way to make this class to always return the same results? I see that `random_state` is already set to 0 but it always gives different values in the end.

### CODE REVIEW

**Comment by MaLiN2223** [comment]
All merge conflicts are resolved

**Comment by cenyk1230** [comment]
Thanks a lot.
Do we really need to use this class format for testing? I think function-based pytest is fine and flexible.

**Comment by MaLiN2223** [comment]
We don't *have to* but class format gives an opportunity to cache result and use it between tests in an encapsulated manner. 
If we were to execute the training on every function call here, all test would take ages

**Comment by cenyk1230** [comment]
I'm thinking about the solution to fast and reasonable testing. The current testing really takes much time. Maybe we should decouple the testing of tasks and models. For each task, we only run once to ensure the format of the result is correct. And we can test each model independently and more fast.

**Comment by MaLiN2223** [comment]
@cenyk1230 that's a good idea and we definitely need to do that - I tried to make the tests parallel but (I think) because of data download they fail (https://github.com/THUDM/cogdl/pull/77)

**Comment by MaLiN2223** [comment]
@cenyk1230 started to address that in https://github.com/THUDM/cogdl/pull/81 for deepwalk.
Should I keep this PR open or close it? 
It will be a long time before the models are tested separately to the dataset so I think class tradeoff is worth it so I personally would merge this PR and in the future change it to functional.

**Comment by cenyk1230** [comment]
Thanks! I will merge it.

**Pull request merged**
