### PR TITLE
Revise for GCC

### PR DESCRIPTION
**Pull request by hwangyeong**
## Description

Revised GCC to make it more in line with the idea of his original paper

## Checklist
Please feel free to remove inapplicable items for your PR.
- gcc_mw
- gcc_dw
- sampling
- bug fixed
- ...

### CODE REVIEW

**Comment by hwangyeong** [comment]
update gcc

**Comment by hwangyeong** [comment]
update gcc

**Review by cenyk1230 — COMMENTED** [review]
What's the meaning of first_restart in the random walk function?

**Review by cenyk1230 — APPROVED** [review]
The pull request successfully implement the GCC model.

**Pull request closed without merging**
