### PR TITLE
Adding DropEdge GCN model

### PR DESCRIPTION
**Pull request by JiaYiLiJayee**
Adding DropEdge GCN model
Adding unit test for dropedge_gcn
Adding DropEdge GCN to examples
Modifying match.yaml to contain dropedge_gcn

### CODE REVIEW

**Comment by JiaYiLiJayee** [comment]
bf65bf0ac6f1ed67fd2cb9b0fb94554
Internal Error in Black failed the check.

**Comment by cenyk1230** [comment]
Hi @JiaYiLiJayee,
It works but the coverage decreases. Please help to increase the coverage.

**Comment by JiaYiLiJayee** [comment]
@cenyk1230 
image
Seems like the unit test from last merge failed?

**Comment by cenyk1230** [comment]
@JiaYiLiJayee,
Sorry, I will try to fix it soon.

**Comment by JiaYiLiJayee** [comment]
@cenyk1230 
is this okay?

**Pull request merged**
