### PR TITLE
Created docker container for easy installation of the repo

### PR DESCRIPTION
**Pull request by TiagoMAntunes**
Hi, I created a docker container when developing a model and decided to share it here. let me know if you run into any problems when running it.

### CODE REVIEW

**Comment by cenyk1230** [comment]
Hi @TiagoMAntunes,

Thank you for your contribution. But I find some errors when building a docker image. Are there any suggestions about the errors?
image

**Comment by TiagoMAntunes** [comment]
I ran into that problem when building it on the AWS server. Building locally worked fine tho, as there were no limitations of the repo to be searched for. This is supposed to be an extra help for those who can't manage to run it locally

Maybe we can switch and have this docker image here but actually publish it. This way only 1 person needs to compile it and just keep it updated.

If you're able to try on your local machine let me know. It built in mine (Windows WSL Ubuntu) I can try and run in another computer

**Comment by TiagoMAntunes** [comment]
I just tried to build the image on my local computer and it worked. Here's proof that it find it: https://prnt.sc/vs5mh0 
(Sorry I didn't manage to get he image URL)

**Comment by TiagoMAntunes** [comment]
There's a [similar problem online](https://stackoverflow.com/questions/39623686/docker-build-ends-with-error-the-command-returned-a-non-zero-code-100) maybe you can try to clean the cache?

**Comment by cenyk1230** [comment]
Thanks a lot. 
I just tried and found it almost worked in my local machine. But `torch==1.7.0+cu102` raised an error `No matching distribution found for torch==1.7.0+cu102`. The version `torch==1.7.0+cu102` might be installed as `torch==1.7.0`. `torch==1.7.0+cpu` is fine. So I change to cuda version of the example to `cu101`.

**Comment by TiagoMAntunes** [comment]
Great, thanks a lot!

**Pull request merged**
