### PR TITLE
Implementation of SIGN model

### PR DESCRIPTION
**Pull request by hmartelb**
This PR contains the implementation of [SIGN: Scalable Inception Graph Neural Networks](https://arxiv.org/pdf/2004.11198.pdf).

### CODE REVIEW

**Comment by cenyk1230** [comment]
Hi @hmartelb,

It seems that it lacks some hyper-parameters in the testing.

**Comment by hmartelb** [comment]
Hi @cenyk1230 ,
Is this ready to merge?

**Comment by cenyk1230** [comment]
Hi @hmartelb,
It seems that the coverage of the code is not so good (77.89% from https://coveralls.io/builds/35355800). It would be better if the coverage is greater than the current coverage of the cogdl (around 81%).

**Comment by cenyk1230** [comment]
Well done!

**Pull request merged**
