### PR TITLE
Added HGP-SL model

### PR DESCRIPTION
**Pull request by Sahandfer**
This is the implementation of the [HGP-SL model](https://arxiv.org/abs/1911.05954)

### CODE REVIEW

**Comment by cenyk1230** [comment]
Good Job. Do you get any results of the implemented HGP-SL model?

**Comment by Sahandfer** [comment]
> Good Job. Do you get any results of the implemented HGP-SL model?
I have not been able to reproduce the results given in the paper. Please refer to my [issue](https://github.com/THUDM/cogdl/issues/83) for further details. Thank you

**Comment by Sahandfer** [comment]
@cenyk1230 I have added the results to the README.md file:
1. The results are from training and testing via k-folds, with 10 folds.
2. For IMDB-b and IMDB-m datasets, the degree-feature argument was set to TRUE.
3. The batch_size was set to 20 (originally 64) to support all datasets.

**Comment by cenyk1230** [comment]
Well done!

**Pull request merged**
